version: '2'
services:
  db:
    image: redis
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - "db"
    environment:
      - MONGODB_HOST=db
  api: 
    image: node
    ports:
      - "3000:3000"
  api2: 
    build: git@github.com/Runnable/docs
    ports:
      - "3000:3000"
    
    
