version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - "db"
    command: npm start
    environment:
      - API_HOST=api:3000
  db:
    image: mongo
    ports:
      - "27017:27017"
  web2:
    build:
      context: git@github.com:Runnable/rails-starter.git
    ports:
      - "3000"
    links:
      - "db"
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
    command: ["bash", "wait-for-postgres-then-run.sh"]
  db1:
    image: mongo
    ports:
      - "27017:27017"
  db2:
    image: postgres
    ports:
      - "5432:5432"
