version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    links:
      - "db"
    command: npm start
    environment:
      - API_HOST=api:3000
  db:
    image: mongo
    ports:
      - "27017:27017"

